/**
 * Tests for scripts/gemini.js Node->Python bridge
 */

const assert = require('assert');
const fs = require('fs');
const path = require('path');
const os = require('os');
const { spawnSync } = require('child_process');

const REPO_ROOT = path.join(__dirname, '..', '..');
const BRIDGE = path.join(REPO_ROOT, 'scripts', 'gemini.js');
const VENV_PYTHON = os.platform() === 'win32'
  ? path.join(REPO_ROOT, '.venv', 'Scripts', 'python.exe')
  : path.join(REPO_ROOT, '.venv', 'bin', 'python3');

function venvAvailable() {
  try {
    return fs.statSync(VENV_PYTHON).isFile();
  } catch (_err) {
    return false;
  }
}

function test(name, fn) {
  try {
    fn();
    console.log(`  ✓ ${name}`);
    return { passed: true, skipped: false };
  } catch (error) {
    console.log(`  ✗ ${name}`);
    console.log(`    Error: ${error.message}`);
    return { passed: false, skipped: false };
  }
}

function skip(name, reason) {
  console.log(`  - skipped ${name}; ${reason}`);
  return { passed: true, skipped: true };
}

function runTests() {
  console.log('\n=== Testing scripts/gemini.js bridge ===\n');

  let passed = 0;
  let failed = 0;
  let skipped = 0;

  function record(result) {
    if (result.skipped) {
      skipped++;
      passed++;
      return;
    }
    if (result.passed) {
      passed++;
    } else {
      failed++;
    }
  }

  record(test('scripts/gemini.js bridge is syntactically valid', () => {
    const result = spawnSync('node', ['--check', BRIDGE], {
      encoding: 'utf8',
      stdio: ['pipe', 'pipe', 'pipe'],
    });
    assert.strictEqual(result.status, 0, `node --check failed: ${result.stderr}`);
  }));

  record(test('scripts/gemini.js declares the canonical env propagation surface', () => {
    const source = fs.readFileSync(BRIDGE, 'utf8');
    const required = [
      'EGC_SESSION_ID',
      'ECC_SESSION_ID',
      'PYTHONPATH',
      'EGC_PLUGIN_ROOT',
      'ECC_PLUGIN_ROOT',
      'PROJECT_ROOT',
    ];
    for (const token of required) {
      assert.ok(
        source.includes(token),
        `scripts/gemini.js must reference ${token} to document its env propagation surface`
      );
    }
  }));

  record(test('scripts/gemini.js does not embed personal absolute paths or AI attribution', () => {
    const source = fs.readFileSync(BRIDGE, 'utf8');

    const homeMatches = source.match(/\/home\/[A-Za-z0-9_.-]+/g) || [];
    assert.strictEqual(
      homeMatches.length,
      0,
      `scripts/gemini.js must not embed absolute /home/<user> paths; found: ${homeMatches.join(', ')}`
    );

    const attribution = /(Claude|Anthropic|Sonnet|Opus|Copilot|generated by|Co-Authored)/i;
    assert.ok(
      !attribution.test(source),
      'scripts/gemini.js must not contain AI attribution markers'
    );
  }));

  if (!venvAvailable()) {
    record(skip('bridge --help reaches the Python entry without requiring a provider key', `${VENV_PYTHON} not present`));
  } else {
    record(test('bridge --help reaches the Python entry without requiring a provider key', () => {
      const env = { ...process.env };
      delete env.GEMINI_API_KEY;
      delete env.GOOGLE_API_KEY;
      delete env.ANTHROPIC_API_KEY;
      delete env.OPENAI_API_KEY;

      const result = spawnSync('node', [BRIDGE, '--help'], {
        cwd: REPO_ROOT,
        env,
        encoding: 'utf8',
        stdio: ['pipe', 'pipe', 'pipe'],
        timeout: 15000,
      });

      assert.strictEqual(result.status, 0, `bridge --help failed (status=${result.status}, stderr=${result.stderr})`);
      assert.ok(
        result.stdout.includes('usage: prompt.py'),
        `bridge --help stdout should include "usage: prompt.py"; got: ${result.stdout}`
      );
      assert.ok(
        result.stdout.includes('--prompt'),
        `bridge --help stdout should include "--prompt"; got: ${result.stdout}`
      );
    }));
  }

  if (!venvAvailable()) {
    record(skip('bridge exits non-zero when no -p flag is provided', `${VENV_PYTHON} not present`));
  } else {
    record(test('bridge exits non-zero when no -p flag is provided', () => {
      const result = spawnSync('node', [BRIDGE], {
        cwd: REPO_ROOT,
        encoding: 'utf8',
        stdio: ['pipe', 'pipe', 'pipe'],
        timeout: 15000,
      });

      assert.notStrictEqual(
        result.status,
        0,
        `bridge with no -p flag should exit non-zero; got status=${result.status}, stdout=${result.stdout}, stderr=${result.stderr}`
      );
    }));
  }

  console.log(`\nResults: Passed: ${passed - skipped}, Skipped: ${skipped}, Failed: ${failed}`);
  process.exit(failed > 0 ? 1 : 0);
}

runTests();
